### ISSUE TITLE
Find alternative to add information to .ips and .urls files

### ISSUE THREAD

**Issue by iitzco** [SonarWAN/sonarwan#16]
Not only get the name of the service with the file's name.

**Comment by iitzco** [comment]
Unify under YAML files.

Example:

``` yaml
Name: Facebook
Type: Social Network
IPs:
- ...
- ...
URLS:
-...
-...
```
